# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 19:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nome da conta')),
                ('description', models.CharField(max_length=200)),
                ('acc_type', models.CharField(choices=[('BK', 'Banco'), ('EX', 'Despesa'), ('IN', 'Recurso')], default='EX', max_length=2, verbose_name='tipo')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='saldo')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='data')),
                ('description', models.CharField(max_length=200, verbose_name='descri\xe7\xe3o')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='valor')),
                ('acc_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taken', to='financial.Account', verbose_name='conta debitada')),
                ('acc_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='added', to='financial.Account', verbose_name='conta creditada')),
            ],
        ),
    ]
